-- Fix typecheck for _system.lua
--- @alias uv.uv_process_t uv_process_t
--- @alias uv.uv_timer_t uv_timer_t
--- @alias uv.uv_stream_t uv_stream_t
--- @alias uv.uv_handle_t uv_handle_t
--- @alias uv.spawn.options table<any, any>
